// ─── Seed data — powers every page without a real backend ─────────────────────
import type { User, Listing, Comment, Notification, Offer } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'lorem_q8',
    email: 'layla@example.com',
    displayName: 'Layla Al-Ahmad',
    avatar: 'https://i.pravatar.cc/150?img=47',
    headerImage: 'https://picsum.photos/seed/header-u1/800/300',
    bio: 'Kuwait City fashionista 💅 Premium pieces only. Speedy shipping. Bundle & save!',
    location: 'Kuwait City, Kuwait',
    followersCount: 1240,
    followingCount: 432,
    listingsCount: 87,
    soldCount: 203,
    averageRating: 4.9,
    totalRatings: 189,
    joinedAt: '2022-03-15T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'u2',
    username: 'ipsum_style',
    email: 'noura@example.com',
    displayName: 'Noura Hassan',
    avatar: 'https://i.pravatar.cc/150?img=32',
    headerImage: 'https://picsum.photos/seed/header-u2/800/300',
    bio: 'Luxury reseller | All items authenticated ✓',
    location: 'Salmiya, Kuwait',
    followersCount: 3820,
    followingCount: 210,
    listingsCount: 142,
    soldCount: 651,
    averageRating: 5.0,
    totalRatings: 512,
    joinedAt: '2021-08-01T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'u3',
    username: 'dolor.fits',
    email: 'khalid@example.com',
    displayName: 'Khalid Al-Mutairi',
    avatar: 'https://i.pravatar.cc/150?img=12',
    headerImage: 'https://picsum.photos/seed/header-u3/800/300',
    bio: 'Menswear enthusiast. Kuwait📍',
    location: 'Hawalli, Kuwait',
    followersCount: 520,
    followingCount: 890,
    listingsCount: 34,
    soldCount: 78,
    averageRating: 4.7,
    totalRatings: 64,
    joinedAt: '2023-01-20T00:00:00Z',
    isVerified: false,
  },
  {
    id: 'u4',
    username: 'amet_closet',
    email: 'maryam@example.com',
    displayName: 'Maryam Al-Rashidi',
    avatar: 'https://i.pravatar.cc/150?img=23',
    headerImage: 'https://picsum.photos/seed/header-u4/800/300',
    bio: 'Modest fashion | Abayas, Shaylas & everyday chic. Based in Jahra 🌸',
    location: 'Al Jahra, Kuwait',
    followersCount: 2100,
    followingCount: 654,
    listingsCount: 196,
    soldCount: 412,
    averageRating: 4.8,
    totalRatings: 340,
    joinedAt: '2021-11-05T00:00:00Z',
    isVerified: true,
  },
];

export const CURRENT_USER_ID = 'u1';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'ipsum_style', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Lorem Classic Flap Bag — Medium — Black',
    description: 'Stunning classic flap in black leather with gold hardware. Purchased from boutique. Comes with box, dustbag, authenticity card, and receipt. Minor wear on hardware — otherwise immaculate. Measurements: 25 × 15 × 7 cm.',
    images: [
      'https://picsum.photos/seed/l1-a/600/600',
      'https://picsum.photos/seed/l1-b/600/600',
      'https://picsum.photos/seed/l1-c/600/600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Lorem',
    size: 'One Size',
    condition: 'Excellent',
    color: ['Black'],
    originalPrice: 1850,
    listingPrice: 1400,
    quantity: 1,
    tags: ['lorem', 'luxury', 'handbag', 'classic flap'],
    likesCount: 284,
    commentsCount: 12,
    sharesCount: 43,
    viewsCount: 1820,
    status: 'available',
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l2',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'lorem_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'Ipsum Floral Midi Dress — Size S — Worn Once',
    description: 'Beautiful floral print midi dress. Worn to one event and dry-cleaned. Perfect condition. Elastic waist with adjustable tie. Fabric: 100% viscose — lightweight and flowy.',
    images: [
      'https://picsum.photos/seed/l2-a/600/600',
      'https://picsum.photos/seed/l2-b/600/600',
    ],
    category: 'Women',
    subCategory: 'Dresses',
    brand: 'Ipsum',
    size: 'S',
    condition: 'NWOT',
    color: ['Multicolor', 'White'],
    originalPrice: 35,
    listingPrice: 18,
    quantity: 1,
    tags: ['ipsum', 'dress', 'floral', 'midi', 'spring'],
    likesCount: 67,
    commentsCount: 4,
    sharesCount: 8,
    viewsCount: 340,
    status: 'available',
    createdAt: '2024-11-03T14:00:00Z',
    updatedAt: '2024-11-03T14:00:00Z',
    isLikedByCurrentUser: true,
  },
  {
    id: 'l3',
    sellerId: 'u4',
    seller: { id: 'u4', username: 'amet_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23', isVerified: true },
    title: 'Embroidered Abaya — Dolor Style — Size M',
    description: 'Hand-embroidered open abaya in premium crepe fabric. Gold thread embroidery on sleeves and hem. Free-flowing, modest, and elegant. Fits M–L. Worn twice.',
    images: [
      'https://picsum.photos/seed/l3-a/600/600',
      'https://picsum.photos/seed/l3-b/600/600',
    ],
    category: 'Women',
    subCategory: 'Abayas',
    brand: 'Dolor Atelier',
    size: 'M',
    condition: 'Good',
    color: ['Black', 'Gold'],
    originalPrice: 120,
    listingPrice: 75,
    quantity: 1,
    tags: ['abaya', 'embroidered', 'modest fashion', 'crepe'],
    likesCount: 143,
    commentsCount: 9,
    sharesCount: 22,
    viewsCount: 890,
    status: 'available',
    createdAt: '2024-10-28T09:00:00Z',
    updatedAt: '2024-10-28T09:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l4',
    sellerId: 'u3',
    seller: { id: 'u3', username: 'dolor.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12', isVerified: false },
    title: 'Amet Air High OG Sneaker — "Classic" — Size 42',
    description: 'DS (Deadstock) classic colorway. Never worn, original box with both lace sets. Size 42 EU / 8.5 US.',
    images: [
      'https://picsum.photos/seed/l4-a/600/600',
      'https://picsum.photos/seed/l4-b/600/600',
    ],
    category: 'Men',
    subCategory: 'Sneakers',
    brand: 'Amet',
    size: '42',
    condition: 'NWT',
    color: ['Red', 'White', 'Black'],
    originalPrice: 165,
    listingPrice: 320,
    quantity: 1,
    tags: ['amet', 'sneakers', 'deadstock', 'ds'],
    likesCount: 211,
    commentsCount: 18,
    sharesCount: 56,
    viewsCount: 2100,
    status: 'available',
    createdAt: '2024-10-30T11:30:00Z',
    updatedAt: '2024-10-30T11:30:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l5',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'ipsum_style', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Sit Mini Top Handle Bag — Rose Beige',
    description: 'Sit mini top handle in matelassé rose beige leather. Double hardware. Comes with original dustbag and box. Strap included for crossbody wear. Light marks on base — reflected in price.',
    images: [
      'https://picsum.photos/seed/l5-a/600/600',
      'https://picsum.photos/seed/l5-b/600/600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Sit',
    size: 'One Size',
    condition: 'Good',
    color: ['Beige', 'Pink'],
    originalPrice: 1250,
    listingPrice: 880,
    quantity: 1,
    tags: ['sit', 'top handle', 'luxury', 'bag'],
    likesCount: 198,
    commentsCount: 7,
    sharesCount: 31,
    viewsCount: 1540,
    status: 'available',
    createdAt: '2024-11-02T16:00:00Z',
    updatedAt: '2024-11-02T16:00:00Z',
    isLikedByCurrentUser: true,
  },
  {
    id: 'l6',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'lorem_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'Consectetur Oversized Blazer — Camel — Size XS',
    description: 'Premium camel blazer. Oversized fit, single button closure. Fully lined. Perfect for the office or casual styling over a dress. Worn twice, excellent condition.',
    images: [
      'https://picsum.photos/seed/l6-a/600/600',
    ],
    category: 'Women',
    subCategory: 'Blazers & Jackets',
    brand: 'Consectetur',
    size: 'XS',
    condition: 'Excellent',
    color: ['Camel', 'Beige'],
    originalPrice: 45,
    listingPrice: 22,
    quantity: 1,
    tags: ['consectetur', 'blazer', 'camel', 'office', 'oversized'],
    likesCount: 34,
    commentsCount: 2,
    sharesCount: 5,
    viewsCount: 180,
    status: 'available',
    createdAt: '2024-11-04T08:00:00Z',
    updatedAt: '2024-11-04T08:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l7',
    sellerId: 'u4',
    seller: { id: 'u4', username: 'amet_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23', isVerified: true },
    title: 'Kids — Adipiscing 3-Piece Pyjama Set — Age 4T',
    description: 'Adorable cotton pyjama set. Long sleeve top + pants + shorts. Glow-in-the-dark dinosaur print. Machine washable. Age 4T. Worn a handful of times, no stains or damage.',
    images: [
      'https://picsum.photos/seed/l7-a/600/600',
    ],
    category: 'Kids',
    subCategory: 'Pyjamas & Sleepwear',
    brand: 'Adipiscing',
    size: '4T',
    condition: 'Good',
    color: ['Blue', 'Green'],
    originalPrice: 28,
    listingPrice: 10,
    quantity: 1,
    tags: ['adipiscing', 'kids', 'pyjamas', 'dinosaur', 'cotton'],
    likesCount: 22,
    commentsCount: 1,
    sharesCount: 3,
    viewsCount: 120,
    status: 'available',
    createdAt: '2024-11-05T12:00:00Z',
    updatedAt: '2024-11-05T12:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l8',
    sellerId: 'u3',
    seller: { id: 'u3', username: 'dolor.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12', isVerified: false },
    title: 'Elit Slim Shirt — Navy Blue — Size M',
    description: 'Classic slim-fit button-down in navy blue. 100% cotton. Worn 3 times, freshly ironed. No fading or pilling. Collar is crisp.',
    images: [
      'https://picsum.photos/seed/l8-a/600/600',
    ],
    category: 'Men',
    subCategory: 'Shirts',
    brand: 'Elit',
    size: 'M',
    condition: 'Excellent',
    color: ['Navy'],
    originalPrice: 95,
    listingPrice: 45,
    quantity: 1,
    tags: ['elit', 'shirt', 'navy', 'slim fit'],
    likesCount: 48,
    commentsCount: 3,
    sharesCount: 6,
    viewsCount: 290,
    status: 'available',
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l9',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'ipsum_style', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Tempor Neverfull MM — Damier Canvas',
    description: 'Tempor Neverfull MM in iconic Damier canvas. Interior spotless. Handles have light patina from use.',
    images: [
      'https://picsum.photos/seed/l9-a/600/600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Tempor',
    size: 'One Size',
    condition: 'Good',
    color: ['Brown', 'Tan'],
    originalPrice: 1600,
    listingPrice: 1050,
    quantity: 1,
    tags: ['tempor', 'tote', 'luxury'],
    likesCount: 310,
    commentsCount: 21,
    sharesCount: 68,
    viewsCount: 3200,
    status: 'sold',
    createdAt: '2024-10-15T14:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l10',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'lorem_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'Incididunt Lipstick Bundle — 5 Shades — Barely Used',
    description: 'Selling 5 lipsticks as a bundle. Each used 1–3 times. All sanitized. Great value.',
    images: [
      'https://picsum.photos/seed/l10-a/600/600',
    ],
    category: 'Beauty',
    subCategory: 'Lip',
    brand: 'Incididunt',
    size: 'One Size',
    condition: 'Good',
    color: ['Red', 'Pink', 'Nude'],
    originalPrice: 60,
    listingPrice: 28,
    quantity: 1,
    tags: ['incididunt', 'lipstick', 'bundle', 'beauty', 'makeup'],
    likesCount: 89,
    commentsCount: 6,
    sharesCount: 14,
    viewsCount: 480,
    status: 'available',
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2024-11-05T10:00:00Z',
    isLikedByCurrentUser: false,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    listingId: 'l1',
    authorId: 'u1',
    author: { id: 'u1', username: 'lorem_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47' },
    body: 'Is the serial still intact? Would love more photos of the interior!',
    createdAt: '2024-11-02T08:00:00Z',
    mentions: [],
  },
  {
    id: 'c2',
    listingId: 'l1',
    authorId: 'u2',
    author: { id: 'u2', username: 'ipsum_style', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32' },
    body: '@lorem_q8 Yes, serial sticker is 100% intact! Adding interior photos now 📸',
    createdAt: '2024-11-02T08:30:00Z',
    mentions: ['lorem_q8'],
  },
  {
    id: 'c3',
    listingId: 'l1',
    authorId: 'u4',
    author: { id: 'u4', username: 'amet_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23' },
    body: 'Stunning piece! Does it come with the authenticity card?',
    createdAt: '2024-11-02T09:00:00Z',
    mentions: [],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'new_like',
    actorId: 'u2',
    actor: { id: 'u2', username: 'ipsum_style', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32' },
    listingId: 'l2',
    listing: { id: 'l2', title: 'Ipsum Floral Midi Dress', images: ['https://picsum.photos/seed/l2-a/100/100'] },
    read: false,
    createdAt: '2024-11-05T11:00:00Z',
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'new_follower',
    actorId: 'u3',
    actor: { id: 'u3', username: 'dolor.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12' },
    read: false,
    createdAt: '2024-11-05T10:00:00Z',
  },
  {
    id: 'n3',
    userId: 'u1',
    type: 'new_offer',
    actorId: 'u4',
    actor: { id: 'u4', username: 'amet_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23' },
    listingId: 'l6',
    listing: { id: 'l6', title: 'Consectetur Oversized Blazer', images: ['https://picsum.photos/seed/l6-a/100/100'] },
    read: true,
    createdAt: '2024-11-04T15:00:00Z',
  },
];

export const MOCK_OFFER: Offer = {
  id: 'o1',
  listingId: 'l1',
  buyerId: 'u1',
  buyer: { id: 'u1', username: 'lorem_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47' },
  amount: 1250,
  status: 'pending',
  message: 'Would you accept 1,250 KWD? I can pick it up today from Salmiya.',
  expiresAt: '2024-11-06T10:00:00Z',
  createdAt: '2024-11-05T10:00:00Z',
};

// Shipping fee model (flat-rate, Poshmark-style)
export const PLATFORM_FEE_RATE = 0.20;  // 20% of sale price
export const SHIPPING_FEE_KWD  = 1.500; // 1.500 KWD flat

export function calcEarnings(salePrice: number) {
  const platformFee    = Math.round(salePrice * PLATFORM_FEE_RATE * 1000) / 1000;
  const sellerEarnings = Math.round((salePrice - platformFee) * 1000) / 1000;
  return { platformFee, sellerEarnings };
}
