// ─── Seed data — powers every page without a real backend ─────────────────────
import type { User, Listing, Comment, Notification, Offer } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'fashionista_q8',
    email: 'layla@example.com',
    displayName: 'Layla Al-Ahmad',
    avatar: 'https://i.pravatar.cc/150?img=47',
    headerImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    bio: 'Kuwait City fashionista 💅 Premium pieces only. Speedy shipping. Bundle & save!',
    location: 'Kuwait City, Kuwait',
    followersCount: 1240,
    followingCount: 432,
    listingsCount: 87,
    soldCount: 203,
    averageRating: 4.9,
    totalRatings: 189,
    joinedAt: '2022-03-15T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'u2',
    username: 'stylebynoura',
    email: 'noura@example.com',
    displayName: 'Noura Hassan',
    avatar: 'https://i.pravatar.cc/150?img=32',
    headerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    bio: 'Luxury reseller | Chanel, Gucci, LV | All items authenticated ✓',
    location: 'Salmiya, Kuwait',
    followersCount: 3820,
    followingCount: 210,
    listingsCount: 142,
    soldCount: 651,
    averageRating: 5.0,
    totalRatings: 512,
    joinedAt: '2021-08-01T00:00:00Z',
    isVerified: true,
  },
  {
    id: 'u3',
    username: 'khalid.fits',
    email: 'khalid@example.com',
    displayName: 'Khalid Al-Mutairi',
    avatar: 'https://i.pravatar.cc/150?img=12',
    headerImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    bio: 'Menswear enthusiast. Zara, H&M, occasional designer. Kuwait📍',
    location: 'Hawalli, Kuwait',
    followersCount: 520,
    followingCount: 890,
    listingsCount: 34,
    soldCount: 78,
    averageRating: 4.7,
    totalRatings: 64,
    joinedAt: '2023-01-20T00:00:00Z',
    isVerified: false,
  },
  {
    id: 'u4',
    username: 'maryam_closet',
    email: 'maryam@example.com',
    displayName: 'Maryam Al-Rashidi',
    avatar: 'https://i.pravatar.cc/150?img=23',
    headerImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800',
    bio: 'Modest fashion | Abayas, Shaylas & everyday chic. Based in Jahra 🌸',
    location: 'Al Jahra, Kuwait',
    followersCount: 2100,
    followingCount: 654,
    listingsCount: 196,
    soldCount: 412,
    averageRating: 4.8,
    totalRatings: 340,
    joinedAt: '2021-11-05T00:00:00Z',
    isVerified: true,
  },
];

export const CURRENT_USER_ID = 'u1';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'stylebynoura', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Chanel Classic Flap Bag — Medium — Black Caviar',
    description: 'Absolutely stunning Chanel Classic Flap in black caviar leather with gold hardware. Purchased from the Chanel boutique in Dubai Mall. Comes with box, dustbag, authenticity card, and receipt. Serial sticker intact. Minor wear on hardware — otherwise immaculate. Measurements: 25 × 15 × 7 cm.',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Chanel',
    size: 'One Size',
    condition: 'Excellent',
    color: ['Black'],
    originalPrice: 1850,
    listingPrice: 1400,
    quantity: 1,
    tags: ['chanel', 'luxury', 'handbag', 'classic flap', 'caviar'],
    likesCount: 284,
    commentsCount: 12,
    sharesCount: 43,
    viewsCount: 1820,
    status: 'available',
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l2',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'fashionista_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'Zara Floral Midi Dress — Size S — Worn Once',
    description: 'Beautiful floral print midi dress from Zara\'s Spring collection. Worn to one event and dry-cleaned. Perfect condition. Elastic waist with adjustable tie. Fabric: 100% viscose — lightweight and flowy.',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
    ],
    category: 'Women',
    subCategory: 'Dresses',
    brand: 'Zara',
    size: 'S',
    condition: 'NWOT',
    color: ['Multicolor', 'White'],
    originalPrice: 35,
    listingPrice: 18,
    quantity: 1,
    tags: ['zara', 'dress', 'floral', 'midi', 'spring'],
    likesCount: 67,
    commentsCount: 4,
    sharesCount: 8,
    viewsCount: 340,
    status: 'available',
    createdAt: '2024-11-03T14:00:00Z',
    updatedAt: '2024-11-03T14:00:00Z',
    isLikedByCurrentUser: true,
  },
  {
    id: 'l3',
    sellerId: 'u4',
    seller: { id: 'u4', username: 'maryam_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23', isVerified: true },
    title: 'Embroidered Abaya — Dubai Style — Size M',
    description: 'Hand-embroidered open abaya in premium crepe fabric. Gold thread embroidery on sleeves and hem. Ordered custom from a Dubai atelier. Free-flowing, modest, and elegant. Fits M–L. Worn twice.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4d57?w=600',
      'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=600',
    ],
    category: 'Women',
    subCategory: 'Abayas',
    brand: 'Custom Atelier',
    size: 'M',
    condition: 'Good',
    color: ['Black', 'Gold'],
    originalPrice: 120,
    listingPrice: 75,
    quantity: 1,
    tags: ['abaya', 'embroidered', 'modest fashion', 'dubai', 'crepe'],
    likesCount: 143,
    commentsCount: 9,
    sharesCount: 22,
    viewsCount: 890,
    status: 'available',
    createdAt: '2024-10-28T09:00:00Z',
    updatedAt: '2024-10-28T09:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l4',
    sellerId: 'u3',
    seller: { id: 'u3', username: 'khalid.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12', isVerified: false },
    title: 'Nike Air Jordan 1 Retro High OG — "Chicago" — Size 42',
    description: 'DS (Deadstock) Jordan 1 Chicago colorway. Never worn, original box with both lace sets. Purchased from Nike SNKRS app. Size 42 EU / 8.5 US.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600',
    ],
    category: 'Men',
    subCategory: 'Sneakers',
    brand: 'Nike',
    size: '42',
    condition: 'NWT',
    color: ['Red', 'White', 'Black'],
    originalPrice: 165,
    listingPrice: 320,
    quantity: 1,
    tags: ['jordan', 'nike', 'chicago', 'sneakers', 'deadstock', 'ds'],
    likesCount: 211,
    commentsCount: 18,
    sharesCount: 56,
    viewsCount: 2100,
    status: 'available',
    createdAt: '2024-10-30T11:30:00Z',
    updatedAt: '2024-10-30T11:30:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l5',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'stylebynoura', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Gucci GG Marmont Mini Top Handle Bag — Rose Beige',
    description: 'Gucci Marmont mini top handle in matelassé rose beige leather. Double G hardware. Comes with original dustbag and box. Strap included for crossbody wear. Light marks on base — reflected in price.',
    images: [
      'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Gucci',
    size: 'One Size',
    condition: 'Good',
    color: ['Beige', 'Pink'],
    originalPrice: 1250,
    listingPrice: 880,
    quantity: 1,
    tags: ['gucci', 'marmont', 'top handle', 'luxury', 'bag'],
    likesCount: 198,
    commentsCount: 7,
    sharesCount: 31,
    viewsCount: 1540,
    status: 'available',
    createdAt: '2024-11-02T16:00:00Z',
    updatedAt: '2024-11-02T16:00:00Z',
    isLikedByCurrentUser: true,
  },
  {
    id: 'l6',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'fashionista_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'H&M Oversized Blazer — Camel — Size 34',
    description: 'H&M premium quality camel blazer. Oversized fit, single button closure. Fully lined. Perfect for the office or casual styling over a dress. Size 34 (XS–S). Worn twice, excellent condition.',
    images: [
      'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600',
    ],
    category: 'Women',
    subCategory: 'Blazers & Jackets',
    brand: 'H&M',
    size: 'XS',
    condition: 'Excellent',
    color: ['Camel', 'Beige'],
    originalPrice: 45,
    listingPrice: 22,
    quantity: 1,
    tags: ['hm', 'blazer', 'camel', 'office', 'oversized'],
    likesCount: 34,
    commentsCount: 2,
    sharesCount: 5,
    viewsCount: 180,
    status: 'available',
    createdAt: '2024-11-04T08:00:00Z',
    updatedAt: '2024-11-04T08:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l7',
    sellerId: 'u4',
    seller: { id: 'u4', username: 'maryam_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23', isVerified: true },
    title: 'Kids — Carter\'s 3-Piece Pyjama Set — Age 4T',
    description: 'Adorable Carter\'s cotton pyjama set. Long sleeve top + pants + shorts. Glow-in-the-dark dinosaur print. Machine washable. Age 4T. Worn a handful of times, no stains or damage.',
    images: [
      'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600',
    ],
    category: 'Kids',
    subCategory: 'Pyjamas & Sleepwear',
    brand: "Carter's",
    size: '4T',
    condition: 'Good',
    color: ['Blue', 'Green'],
    originalPrice: 28,
    listingPrice: 10,
    quantity: 1,
    tags: ['carters', 'kids', 'pyjamas', 'dinosaur', 'cotton'],
    likesCount: 22,
    commentsCount: 1,
    sharesCount: 3,
    viewsCount: 120,
    status: 'available',
    createdAt: '2024-11-05T12:00:00Z',
    updatedAt: '2024-11-05T12:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l8',
    sellerId: 'u3',
    seller: { id: 'u3', username: 'khalid.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12', isVerified: false },
    title: 'Polo Ralph Lauren Slim Shirt — Navy Blue — Size M',
    description: 'Classic Ralph Lauren slim-fit button-down in navy blue. 100% cotton. Worn 3 times, freshly ironed. No fading or pilling. Collar is crisp.',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600',
    ],
    category: 'Men',
    subCategory: 'Shirts',
    brand: 'Ralph Lauren',
    size: 'M',
    condition: 'Excellent',
    color: ['Navy'],
    originalPrice: 95,
    listingPrice: 45,
    quantity: 1,
    tags: ['ralph lauren', 'polo', 'shirt', 'navy', 'slim fit'],
    likesCount: 48,
    commentsCount: 3,
    sharesCount: 6,
    viewsCount: 290,
    status: 'available',
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l9',
    sellerId: 'u2',
    seller: { id: 'u2', username: 'stylebynoura', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32', isVerified: true },
    title: 'Louis Vuitton Neverfull MM — Damier Ebene',
    description: 'LV Neverfull MM in iconic Damier Ebene canvas. Rose Ballerine interior. Comes with pochette. Date code: AR5113. Handles have light patina from use — consistent with age. Interior spotless.',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    ],
    category: 'Women',
    subCategory: 'Handbags',
    brand: 'Louis Vuitton',
    size: 'One Size',
    condition: 'Good',
    color: ['Brown', 'Tan'],
    originalPrice: 1600,
    listingPrice: 1050,
    quantity: 1,
    tags: ['louis vuitton', 'neverfull', 'damier', 'lv', 'tote'],
    likesCount: 310,
    commentsCount: 21,
    sharesCount: 68,
    viewsCount: 3200,
    status: 'sold',
    createdAt: '2024-10-15T14:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
    isLikedByCurrentUser: false,
  },
  {
    id: 'l10',
    sellerId: 'u1',
    seller: { id: 'u1', username: 'fashionista_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47', isVerified: true },
    title: 'MAC Lipstick Bundle — 5 Shades — Barely Used',
    description: 'Selling 5 MAC lipsticks as a bundle: Ruby Woo, Whirl, Velvet Teddy, Chili, and Mehr. Each used 1–3 times. All sanitized. Great value for a MAC lover.',
    images: [
      'https://images.unsplash.com/photo-1586495777744-4e6232bf4c0c?w=600',
    ],
    category: 'Beauty',
    subCategory: 'Lip',
    brand: 'MAC',
    size: 'One Size',
    condition: 'Good',
    color: ['Red', 'Pink', 'Nude'],
    originalPrice: 60,
    listingPrice: 28,
    quantity: 1,
    tags: ['mac', 'lipstick', 'bundle', 'beauty', 'makeup'],
    likesCount: 89,
    commentsCount: 6,
    sharesCount: 14,
    viewsCount: 480,
    status: 'available',
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2024-11-05T10:00:00Z',
    isLikedByCurrentUser: false,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    listingId: 'l1',
    authorId: 'u1',
    author: { id: 'u1', username: 'fashionista_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47' },
    body: 'Is the serial still intact? Would love more photos of the interior!',
    createdAt: '2024-11-02T08:00:00Z',
    mentions: [],
  },
  {
    id: 'c2',
    listingId: 'l1',
    authorId: 'u2',
    author: { id: 'u2', username: 'stylebynoura', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32' },
    body: '@fashionista_q8 Yes, serial sticker is 100% intact! Adding interior photos now 📸',
    createdAt: '2024-11-02T08:30:00Z',
    mentions: ['fashionista_q8'],
  },
  {
    id: 'c3',
    listingId: 'l1',
    authorId: 'u4',
    author: { id: 'u4', username: 'maryam_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23' },
    body: 'Stunning piece! Does it come with the authenticity card?',
    createdAt: '2024-11-02T09:00:00Z',
    mentions: [],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'new_like',
    actorId: 'u2',
    actor: { id: 'u2', username: 'stylebynoura', displayName: 'Noura Hassan', avatar: 'https://i.pravatar.cc/150?img=32' },
    listingId: 'l2',
    listing: { id: 'l2', title: 'Zara Floral Midi Dress', images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=100'] },
    read: false,
    createdAt: '2024-11-05T11:00:00Z',
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'new_follower',
    actorId: 'u3',
    actor: { id: 'u3', username: 'khalid.fits', displayName: 'Khalid Al-Mutairi', avatar: 'https://i.pravatar.cc/150?img=12' },
    read: false,
    createdAt: '2024-11-05T10:00:00Z',
  },
  {
    id: 'n3',
    userId: 'u1',
    type: 'new_offer',
    actorId: 'u4',
    actor: { id: 'u4', username: 'maryam_closet', displayName: 'Maryam Al-Rashidi', avatar: 'https://i.pravatar.cc/150?img=23' },
    listingId: 'l6',
    listing: { id: 'l6', title: 'H&M Oversized Blazer', images: ['https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=100'] },
    read: true,
    createdAt: '2024-11-04T15:00:00Z',
  },
];

export const MOCK_OFFER: Offer = {
  id: 'o1',
  listingId: 'l1',
  buyerId: 'u1',
  buyer: { id: 'u1', username: 'fashionista_q8', displayName: 'Layla Al-Ahmad', avatar: 'https://i.pravatar.cc/150?img=47' },
  amount: 1250,
  status: 'pending',
  message: 'Would you accept 1,250 KWD? I can pick it up today from Salmiya.',
  expiresAt: '2024-11-06T10:00:00Z',
  createdAt: '2024-11-05T10:00:00Z',
};

// Shipping fee model (flat-rate, Poshmark-style)
export const PLATFORM_FEE_RATE = 0.20;  // 20% of sale price
export const SHIPPING_FEE_KWD  = 1.500; // 1.500 KWD flat

export function calcEarnings(salePrice: number) {
  const platformFee    = Math.round(salePrice * PLATFORM_FEE_RATE * 1000) / 1000;
  const sellerEarnings = Math.round((salePrice - platformFee) * 1000) / 1000;
  return { platformFee, sellerEarnings };
}
